# Assignment 2: Milestone I Natural Language Processing
## Task 1. Basic Text Pre-processing
#### Student Name - Student ID: 
- Nguyen Trong Tien - s3978616
- Nguyen Hai Long - s4002308
- Vo Nguyen Bao Ngoc - s3975091
- Truong Gia Hy - s4053650

## Contents

1. [Introduction](#introduction)
2. [Environment & Imports](#environment-import)
3. [Data Loading](#data-loading)
- 3.1. [Read and print data](#read-and-print-data)
- 3.2. [Pre-processing data](#pre-processing-data)
4. [Export Vocabulary & Processed Dataset](#export-vocabulary-processed-dataset)

## 1. Introduction <a id="introduction"></a>

In this milestone, the goal is to apply Natural Language Processing (NLP) to a collection of clothing reviews in order to predict product recommendations. The tasks include pre-processing the review text (tokenization, stopword removal, and frequency-based filtering), generating feature representations (Bag-of-Words and word embeddings), and building machine learning models to classify whether a review  indicates a recommendation. Finally, the models will be evaluated and analyzed to determine their effectiveness.

## 2. Environment & Import <a id="environment-import"></a>
### Environment: : Python 3 and Jupyter notebook

Libraries used: 
* pandas
* re
* numpy
* matplotlib
* nltk
* spellchecker
* TextBlob
* Counter
* wordnet
* RegexpTokenizer
* WordNetLemmatizer

### Importing libraries

In [1]:
# Import neccessary libraries for this assessment:
import numpy as np
import matplotlib.pyplot as plt
import os
import re
import zipfile
from textblob import TextBlob
from collections import Counter
from pathlib import Path
from nltk.tokenize import RegexpTokenizer
from nltk.stem import WordNetLemmatizer
from spellchecker import SpellChecker
from nltk.corpus import wordnet
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
from collections import Counter
import pandas as pd

[nltk_data] Downloading package punkt to /Users/vongoc/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/vongoc/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/vongoc/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /Users/vongoc/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/vongoc/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/vongoc/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

## 3. Loading data <a id="data-loading"></a>

### 3.1. Read and print data <a id="read-and-print-data"></a>

In [2]:
# Check data

df = pd.read_csv('assignment3.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19662 entries, 0 to 19661
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Clothing ID              19662 non-null  int64
 1   Age                      19662 non-null  int64
 2   Title                    19662 non-null  object
 3   Review Text              19662 non-null  object
 4   Rating                   19662 non-null  int64
 5   Recommended IND          19662 non-null  int64
 6   Positive Feedback Count  19662 non-null  int64
 7   Division Name            19662 non-null  object
 8   Department Name          19662 non-null  object
 9   Class Name               19662 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.5+ MB

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
1,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
2,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses
3,1080,49,Not for the very petite,"I love tracy reese dresses, but this one is no...",2,0,4,General,Dresses,Dresses
4,858,39,Cagrcoal shimmer fun,I aded this in my basket at hte last mintue to...,5,1,1,General Petite,Tops,Knits

### Insight — Missing values / schema
- **What we checked:** Null counts by column and overall completeness.
- **What to look for:** Features with heavy missingness (>20%) merit imputation strategy notes or removal; MCAR vs MAR hints from patterns across columns.

### **3.2 Pre-processing data** <a id="pre-processing-data"></a>
##### Tokenize & Normalize Review Text  <a id='sec-clean'></a>
Prepare raw review text for modeling by turning it into tokens while avoiding information loss that could hurt downstream classification.

First, we tokenize Review Text into tokens

In [3]:
# Tokenizing clothing review

# define tokenizer and keeps meaningful forms
tokenizer = RegexpTokenizer(r"[a-zA-Z]+(?:[-'][a-zA-Z]+)?")

# Handle missing text and tokenize the review text + lowercasing and removing words with length < 2
df["tokens"] = (
    df["Review Text"]
      .fillna("") # replace NaN with empty string
      .astype(str)
      .apply(lambda text: [token.lower() for token in tokenizer.tokenize(text) if len(token) > 1])
)

# quick spot-checks (delete when done)
print(df["tokens"].head(3).tolist())
assert isinstance(df["tokens"].iloc[0], list)

[['had', 'such', 'high', 'hopes', 'for', 'this', 'dress', 'and', 'really', 'wanted', 'it', 'to', 'work', 'for', 'me', 'initially', 'ordered', 'the', 'petite', 'small', 'my', 'usual', 'size', 'but', 'found', 'this', 'to', 'be', 'outrageously', 'small', 'so', 'small', 'in', 'fact', 'that', 'could', 'not', 'zip', 'it', 'up', 'reordered', 'it', 'in', 'petite', 'medium', 'which', 'was', 'just', 'ok', 'overall', 'the', 'top', 'half', 'was', 'comfortable', 'and', 'fit', 'nicely', 'but', 'the', 'bottom', 'half', 'had', 'very', 'tight', 'under', 'layer', 'and', 'several', 'somewhat', 'cheap', 'net', 'over', 'layers', 'imo', 'major', 'design', 'flaw', 'was', 'the', 'net', 'over', 'layer', 'sewn', 'directly', 'into', 'the', 'zipper', 'it'], ['love', 'love', 'love', 'this', 'jumpsuit', "it's", 'fun', 'flirty', 'and', 'fabulous', 'every', 'time', 'wear', 'it', 'get', 'nothing', 'but', 'great', 'compliments'], ['this', 'shirt', 'is', 'very', 'flattering', 'to', 'all', 'due', 'to', 'the', 'adjustable', 'front', 'tie', 'it', 'is', 'the', 'perfect', 'length', 'to', 'wear', 'with', 'leggings', 'and', 'it', 'is', 'sleeveless', 'so', 'it', 'pairs', 'well', 'with', 'any', 'cardigan', 'love', 'this', 'shirt']]

##### **Text Spelling Correction for Tokenized Data with TextBlob**
Here we try to reduce words having typos and incorrect spellings in reviews by correcting each token to its most probable approriate word

Define functions to initialize TextBlob and apply it to the tokens (this would take time to run)

In [4]:
def correct_text(text):
    return str(TextBlob(text).correct())

def correct_tokens(token_list):
    corrected_tokens = []
    for token in token_list:
        corrected_token = correct_text(token)
        corrected_tokens.append(corrected_token)
    return corrected_tokens

df["tokens"] = df["tokens"].apply(correct_tokens)

##### Spell Checking & Token Cleaning for Tokenized Reviews
Reduce vocabulary noise by lowercasing and removing nulls, then correct misspellings again token-by-token using SpellChecker

Define SpellChecker and apply it to tokens, we use both TextBlob and SpellChecker to reduce as much typo error as possible (this would take time to run)

In [ ]:
spell = SpellChecker()


# Clean tokens
def clean_tokens(tokens):
    if not isinstance(tokens, list):
        return []
    return [str(t).lower() for t in tokens if t is not None]

# Spell checking
def correct_tokens(tokens):
    corrected = []
    for word in tokens:
        if word in spell.unknown([word]):
            suggestion = spell.correction(word)
            corrected.append(suggestion if suggestion is not None else word)
        else:
            corrected.append(word)
    return corrected


# Apply pipeline
df["tokens"] = df["tokens"].apply(clean_tokens)
df["tokens"] = df["tokens"].apply(correct_tokens)

##### Stopword Removal
Remove words provided in stopwords_en.txt

Here we read the file and remove words from that file

In [ ]:
# Remove stopwords using the provided stop words list (i.e., stopwords_en.txt). It is located inside the same downloaded folder. 
# Find file stopwords in data
stop_path = Path("stopwords_en.txt")

# Load stopwords
with open(stop_path, "r", encoding="utf-8") as f:
    stop_words = {line.strip() for line in f if line.strip()}

print(f"[Q5] Loaded {len(stop_words)} stopwords from {stop_path}")

# Remove stopwords (Compare lowercase)
def remove_stopwords(tokens, stopset):
    return [t for t in tokens if t.lower() not in stopset]

df["tokens"] = df["tokens"].apply(remove_stopwords, stopset=stop_words)

# Print to check
print(df[["tokens"]].head(2))

[Q5] Loaded 570 stopwords from stopwords_en.txt
                                              tokens
0  [high, hopes, dress, wanted, work, initially, ...
1  [love, love, love, jumpsuit, fun, flirty, fabu...

##### Token Pruning  
Remove the word that appears only once in the document collection, based on term frequency.  
Remove the top 20 most frequent words based on document frequency.

We read the tokens' term frequencies and keep only those higher than 1

In [ ]:
# Remove the word that appears only once in the document collection, based on term frequency.
term_freq = pd.Series(np.concatenate(df["tokens"].values)).value_counts()
 
df["tokens"] = df["tokens"].apply(lambda tokens: [token for token in tokens if term_freq[token] > 1])

# Double check
term_freq = pd.Series(np.concatenate(df["tokens"].values)).value_counts()
term_freq

dress          9334
size           7860
love           7722
fit            6582
top            6542
               ...
upsize            2
relaxed-fit       2
undressed         2
connected         2
crosswrap         2
Name: count, Length: 7549, dtype: int64

Similarly, we count the document frequencies and remove top 20 highest

In [ ]:
# Remove the top 20 most frequent words based on document frequency. 
# Count document frequency (each word counts only once per doc)
doc_freq = Counter()
for tokens in df["tokens"]:
    unique_tokens = set(tokens)
    doc_freq.update(unique_tokens)

# Get the top 20 most frequent words
top_20_words = {word for word, _ in doc_freq.most_common(20)}
print("Top 20 frequent words:", top_20_words)

# Remove them from each token list
df["tokens"] = df["tokens"].apply(
    lambda tokens: [w for w in tokens if w not in top_20_words]
)

Top 20 frequent words: {'fabric', 'small', 'ordered', 'color', 'top', 'fits', 'fit', 'flattering', 'back', 'nice', 'dress', 'cute', 'soft', 'comfortable', 'perfect', 'bought', 'wear', 'love', 'great', 'size'}

#### Lematization  
Lemmatize tokens to combine relevant words with different suffixes

In [ ]:
# Creates an NLTK WordNet lemmatizer and replaces each token in every review with its lemma
lemmatizer = WordNetLemmatizer()
df["tokens"] = [[lemmatizer.lemmatize(w) for w in review] for review in df["tokens"].tolist()]

We clean the vocabulary again

In [ ]:
# Vocabulary Sanitization
def clean_vocab_token(token):
    token = token.lower().strip()
    if re.fullmatch(r"[a-z0-9]+", token) and len(token) > 2:
        return token
    return None

cleaned_tokens = df["tokens"].apply(lambda tokens: [clean_vocab_token(t) for t in tokens if t is not None])
df["tokens"] = cleaned_tokens.apply(lambda tokens: [t for t in tokens if t is not None])

In [ ]:
# Print to check the tokens column
df[["tokens"]].head(50)

                                               tokens
0   [high, hope, wanted, work, initially, petite, ...
1   [jumpsuit, fun, flirty, fabulous, time, compli...
2   [shirt, due, adjustable, front, tie, length, l...
3   [tracy, reese, dress, petite, foot, tall, bran...
4   [basket, hte, person, store, pick, teh, pale, ...
5   [carbon, store, pick, ton, stuff, pair, skirt,...
6   [run, snug, bust, feminine, usual, retailer, f...
7   [petite, make, length, long, typically, regula...
8   [run, esp, zipper, area, run, typically, tight...
9   [find, review, written, savvy, shopper, past, ...
10  [black, larkspur, midi, bother, lining, skirt,...
11  [choice, holiday, gathering, length, knee, con...
12  [package, wanted, badly, put, figure, straight...
13  [material, leg, opening, large, length, hit, a...
14  [chance, blouse, glad, crazy, blouse, photogra...
15  [super, cozy, coat, work, cold, dry, day, good...
16  [feel, tulle, eve, chested, form, fitting, ste...
17  [product, petite, petite, regular, long, tailo...
18  [upset, price, thought, embroidered, print, op...
19  [pullover, styling, side, zipper, purchased, k...
20  [high, waisted, good, length, height, dont, fe...
21  [shirt, shirt, slip, legging, slip, wore, tie,...
22  [loved, material, didnt, long, purchased, larg...
23  [waiting, sweater, coat, ship, week, excited, ...
24  [color, expected, dark, blue, vibrant, find, t...
25          [shirt, compliment, hesitate, buy, shirt]
26  [sweater, comfy, classic, balance, quirky, bea...
27  [pant, online, person, cuter, stripe, brighter...
28             [pant, person, downside, dry, cleaned]
29  [month, ago, finally, order, huge, disappointm...
30  [neat, super, tall, long, length, added, bonus...
31                                      [store, whim]
32  [medium, mom, gorgeous, beautifully, draped, w...
33  [poncho, plaid, check, design, color, sorbet, ...
34  [thermal, naturally, expect, super, sheer, she...
35  [today, local, retailer, bad, picture, online,...
36  [item, online, model, looked, loose, mine, bit...
37    [sweater, fall, roomy, warm, super, comfy, pop]
38  [embroidery, collar, bib, beautiful, unique, r...
39  [transition, easily, summer, fall, print, stor...
40  [absolutely, bib, tee, favorite, retailer, pur...
41  [shirt, unusual, asymmetrical, seam, appears, ...
42  [armhole, bit, oversized, older, woman, picky,...
43  [adorable, find, extremely, buy, print, femini...
44  [tank, loved, ruffle, layed, front, good, retu...
45  [bralettes, provide, support, binding, tight, ...
46  [simply, beautiful, stunning, figure, wait, wo...
47  [tag, sewn, long, huge, itchy, cut, thread, le...
48  [recently, sale, forever, list, happy, long, t...
49  [shirt, light, weight, lovely, floral, color, ...

##### Vocabulary Construction & Global Token Frequency
Build a vocabulary of the cleaned/processed reviews, and save it in a txt file

Flatten all tokens and construct a vocab dictionary

In [ ]:
# Flatten all tokens
all_tokens = [t for tokens in df["tokens"] for t in tokens]

# Sort vocab
unique_vocab = sorted(set(all_tokens))
vocab_dict = {word: idx for idx, word in enumerate(unique_vocab)}
vocab_dict

{'abbey': 0,
 'abby': 1,
 'abdomen': 2,
 'ability': 3,
 'abnormally': 4,
 'abo': 5,
 'abou': 6,
 'abroad': 7,
 'absolute': 8,
 'absolutely': 9,
 'absolutley': 10,
 'absolutly': 11,
 'abstract': 12,
 'absurd': 13,
 'abt': 14,
 'abundance': 15,
 'accent': 16,
 'accented': 17,
 'accenting': 18,
 'accentuate': 19,
 'accentuated': 20,
 'accentuates': 21,
 'accentuating': 22,
 'accept': 23,
 'acceptable': 24,
 'accepted': 25,
 'access': 26,
 'accessorize': 27,
 'accessorized': 28,
 'accessorizing': 29,
 'accessory': 30,
 'accident': 31,
 'accidental': 32,
 'accidentally': 33,
 'accommodate': 34,
 'accommodated': 35,
 'accommodates': 36,
 'accommodating': 37,
 'accomodate': 38,
 'accompanying': 39,
 'accomplish': 40,
 'accordian': 41,
 'account': 42,
 'accurate': 43,
 'accurately': 44,
 'acetate': 45,
 'achieve': 46,
 'acrylic': 47,
 'act': 48,
 'action': 49,
 'active': 50,
 'activewear': 51,
 'activity': 52,
 'actual': 53,
 'actuality': 54,
 'ada': 55,
 'add': 56,
 'added': 57,
 'addict': 58,
 'addicted': 59,
 'adding': 60,
 'addition': 61,
 'additional': 62,
 'additionally': 63,
 'address': 64,
 'adequate': 65,
 'adequately': 66,
 'adjust': 67,
 'adjustable': 68,
 'adjusted': 69,
 'adjusting': 70,
 'adjustment': 71,
 'admire': 72,
 'admired': 73,
 'admiring': 74,
 'admit': 75,
 'admittedly': 76,
 'adn': 77,
 'ador': 78,
 'adorable': 79,
 'adore': 80,
 'adored': 81,
 'adult': 82,
 'advantage': 83,
 'adventure': 84,
 'advertised': 85,
 'advice': 86,
 'advise': 87,
 'advised': 88,
 'aesthetic': 89,
 'aesthetically': 90,
 'affair': 91,
 'affect': 92,
 'affected': 93,
 'afford': 94,
 'affordable': 95,
 'aforementioned': 96,
 'afraid': 97,
 'afternoon': 98,
 'afterward': 99,
 'age': 100,
 'aged': 101,
 'aggressive': 102,
 'agin': 103,
 'ago': 104,
 'agree': 105,
 'agreed': 106,
 'agreement': 107,
 'ahd': 108,
 'ahead': 109,
 'ahhh': 110,
 'ahs': 111,
 'ahve': 112,
 'air': 113,
 'airiness': 114,
 'airing': 115,
 'airplane': 116,
 'airport': 117,
 'airy': 118,
 'aize': 119,
 'aka': 120,
 'akemi': 121,
 'ala': 122,
 'alaska': 123,
 'albeit': 124,
 'alexandria': 125,
 'align': 126,
 'aligned': 127,
 'alike': 128,
 'aline': 129,
 'alittle': 130,
 'alley': 131,
 'allison': 132,
 'allover': 133,
 'allowed': 134,
 'allowing': 135,
 'allusion': 136,
 'alot': 137,
 'alpaca': 138,
 'alright': 139,
 'alter': 140,
 'alteration': 141,
 'altered': 142,
 'altering': 143,
 'alternate': 144,
 'alternation': 145,
 'alternative': 146,
 'altho': 147,
 'altogether': 148,
 'amadi': 149,
 'amalfi': 150,
 'amazed': 151,
 'amazing': 152,
 'amazingly': 153,
 'amazon': 154,
 'ambiguous': 155,
 'amd': 156,
 'american': 157,
 'amount': 158,
 'amp': 159,
 'ample': 160,
 'amply': 161,
 'amterial': 162,
 'anatomy': 163,
 'angel': 164,
 'angeles': 165,
 'angle': 166,
 'angled': 167,
 'angora': 168,
 'animal': 169,
 'ankle': 170,
 'anna': 171,
 'anniversary': 172,
 'annoyance': 173,
 'annoyed': 174,
 'annoying': 175,
 'anorak': 176,
 'answer': 177,
 'ant': 178,
 'anth': 179,
 'anther': 180,
 'antho': 181,
 'anticipate': 182,
 'anticipated': 183,
 'anticipating': 184,
 'anticipation': 185,
 'antique': 186,
 'antrho': 187,
 'antro': 188,
 'anxious': 189,
 'anxiously': 190,
 'anymore': 191,
 'anytime': 192,
 'app': 193,
 'appalled': 194,
 'apparel': 195,
 'apparent': 196,
 'apparently': 197,
 'appeal': 198,
 'appealed': 199,
 'appealing': 200,
 'appearance': 201,
 'appeared': 202,
 'appearing': 203,
 'appears': 204,
 'apple': 205,
 'applied': 206,
 'appliqu': 207,
 'applique': 208,
 'apply': 209,
 'appreciated': 210,
 'apprehensive': 211,
 'approach': 212,
 'approaching': 213,
 'appropriately': 214,
 'approved': 215,
 'approx': 216,
 'approximate': 217,
 'approximately': 218,
 'apprx': 219,
 'apricot': 220,
 'april': 221,
 'apron': 222,
 'apt': 223,
 'aqua': 224,
 'arc': 225,
 'area': 226,
 'aren': 227,
 'arielle': 228,
 'arm': 229,
 'armed': 230,
 'armhole': 231,
 'armpit': 232,
 'army': 233,
 'arranged': 234,
 'arrival': 235,
 'arrive': 236,
 'arrived': 237,
 'arrives': 238,
 'arrow': 239,
 'art': 240,
 'article': 241,
 'artist': 242,
 'artistic': 243,
 'artsy': 244,
 'artwork': 245,
 'asap': 246,
 'ashley': 247,
 'asia': 248,
 'asked': 249,
 'aspect': 250,
 'assessing': 251,
 'asset': 252,
 'assistance': 253,
 'assistant': 254,
 'associate': 255,
 'assume': 256,
 'assumed': 257,
 'assuming': 258,
 'assumption': 259,
 'assured': 260,
 'astounded': 261,
 'asymmetric': 262,
 'asymmetrical': 263,
 'asymmetry': 264,
 'ate': 265,
 'athleisure': 266,
 'athlete': 267,
 'athletic': 268,
 'atl': 269,
 'atlanta': 270,
 'atleast': 271,
 'atrocious': 272,
 'attach': 273,
 'attache': 274,
 'attached': 275,
 'attachment': 276,
 'attempt': 277,
 'attempted': 278,
 'attempting': 279,
 'attend': 280,
 'attendant': 281,
 'attended': 282,
 'attending': 283,
 'attention': 284,
 'attire': 285,
 'attitude': 286,
 'attracted': 287,
 'attracting': 288,
 'attractive': 289,
 'audrey': 290,
 'august': 291,
 'aunt': 292,
 'australian': 293,
 'authentic': 294,
 'automatically': 295,
 'autumn': 296,
 'autumnal': 297,
 'avail': 298,
 'availability': 299,
 'average': 300,
 'avid': 301,
 'avoid': 302,
 'avoided': 303,
 'avoiding': 304,
 'avoids': 305,
 'awaited': 306,
 'awaiting': 307,
 'award': 308,
 'aware': 309,
 'awesome': 310,
 'awful': 311,
 'awhile': 312,
 'awkward': 313,
 'awkwardly': 314,
 'awkwardness': 315,
 'baby': 316,
 'babydoll': 317,
 'bac': 318,
 'bachelorette': 319,
 'back': 320,
 'backed': 321,
 'background': 322,
 'backorder': 323,
 'backordered': 324,
 'backpack': 325,
 'backside': 326,
 'backup': 327,
 'backward': 328,
 'backwards': 329,
 'backyard': 330,
 'bad': 331,
 'badly': 332,
 'bag': 333,
 'bagged': 334,
 'baggie': 335,
 'baggier': 336,
 'bagginess': 337,
 'bagging': 338,
 'baggy': 339,
 'bailey': 340,
 'baily': 341,
 'balance': 342,
 'balanced': 343,
 'balck': 344,
 'balked': 345,
 'ball': 346,
 'ballet': 347,
 'balloon': 348,
 'ballooned': 349,
 'balloony': 350,
 'bam': 351,
 'band': 352,
 'bandage': 353,
 'bandeau': 354,
 'banded': 355,
 'banding': 356,
 'bank': 357,
 'bar': 358,
 'barbecue': 359,
 'bare': 360,
 'barefoot': 361,
 'barely': 362,
 'bargain': 363,
 'barley': 364,
 'baroque': 365,
 'barre': 366,
 'barrel': 367,
 'base': 368,
 'baseball': 369,
 'based': 370,
 'basic': 371,
 'basically': 372,
 'basis': 373,
 'basket': 374,
 'basketball': 375,
 'basketweave': 376,
 'bat': 377,
 'batch': 378,
 'bath': 379,
 'bathing': 380,
 'bathrobe': 381,
 'bathroom': 382,
 'battle': 383,
 'batwing': 384,
 'bay': 385,
 'bbq': 386,
 'bday': 387,
 'bea': 388,
 'beach': 389,
 'beachy': 390,
 'bead': 391,
 'beaded': 392,
 'beading': 393,
 'beadwork': 394,
 'bear': 395,
 'beat': 396,
 'beautifu': 397,
 'beautiful': 398,
 'beautifully': 399,
 'beautify': 400,
 'beauty': 401,
 'bec': 402,
 'beca': 403,
 'becasue': 404,
 'becau': 405,
 'becaus': 406,
 'becuase': 407,
 'bed': 408,
 'bedtime': 409,
 'bee': 410,
 'beef': 411,
 'began': 412,
 'begging': 413,
 'begin': 414,
 'beginning': 415,
 'behold': 416,
 'beige': 417,
 'bein': 418,
 'bel': 419,
 'bell': 420,
 'belled': 421,
 'bellow': 422,
 'belly': 423,
 'bellybutton': 424,
 'belonged': 425,
 'beloved': 426,
 'belt': 427,
 'belted': 428,
 'belting': 429,
 'bend': 430,
 'bending': 431,
 'beneath': 432,
 'benefit': 433,
 'bent': 434,
 'bermuda': 435,
 'berry': 436,
 'bet': 437,
 'bette': 438,
 'betty': 439,
 'beware': 440,
 'bff': 441,
 'bias': 442,
 'biased': 443,
 'bib': 444,
 'bicep': 445,
 'biceps': 446,
 'bicycle': 447,
 'bid': 448,
 'big': 449,
 'bigger': 450,
 'biggest': 451,
 'biggie': 452,
 'biggish': 453,
 'biker': 454,
 'bikini': 455,
 'bill': 456,
 'billow': 457,
 'billowed': 458,
 'billowing': 459,
 'billowy': 460,
 'bind': 461,
 'binder': 462,
 'binding': 463,
 'bingo': 464,
 'bird': 465,
 'birkenstocks': 466,
 'birth': 467,
 'birthday': 468,
 'bit': 469,
 'bite': 470,
 'bitter': 471,
 'bizarre': 472,
 'black': 473,
 'blade': 474,
 'blah': 475,
 'bland': 476,
 'blank': 477,
 'blanket': 478,
 'blazer': 479,
 'blazing': 480,
 'bleach': 481,
 'bleached': 482,
 'bled': 483,
 'bleed': 484,
 'blend': 485,
 'blessed': 486,
 'blight': 487,
 'blindly': 488,
 'bling': 489,
 'blk': 490,
 'bloated': 491,
 'blob': 492,
 'block': 493,
 'blocked': 494,
 'blocking': 495,
 'blog': 496,
 'blogger': 497,
 'blond': 498,
 'blonde': 499,
 'blood': 500,
 'bloom': 501,
 'blossom': 502,
 'blotchy': 503,
 'blouse': 504,
 'bloused': 505,
 'blousey': 506,
 'blousing': 507,
 'blouson': 508,
 'blousy': 509,
 'blow': 510,
 'blown': 511,
 'blowzy': 512,
 'blu': 513,
 'blue': 514,
 'blueish': 515,
 'bluish': 516,
 'bluishgreen': 517,
 'blush': 518,
 'board': 519,
 'boarder': 520,
 'boardwalk': 521,
 'boat': 522,
 'boatneck': 523,
 'bod': 524,
 'bodice': 525,
 'body': 526,
 'bodycon': 527,
 'bodysuit': 528,
 'bodytype': 529,
 'bog': 530,
 'bohemian': 531,
 'boho': 532,
 'boiled': 533,
 'bold': 534,
 'bolder': 535,
 'bolero': 536,
 'bomb': 537,
 'bomber': 538,
 'bone': 539,
 'boned': 540,
 'boning': 541,
 'bonnet': 542,
 'bonus': 543,
 'boo': 544,
 'boob': 545,
 'book': 546,
 'boost': 547,
 'boot': 548,
 'bootcut': 549,
 'bootie': 550,
 'booty': 551,
 'bordeaux': 552,
 'border': 553,
 'bordered': 554,
 'borderline': 555,
 'boring': 556,
 'born': 557,
 'borrow': 558,
 'borrowed': 559,
 'bosom': 560,
 'boston': 561,
 'bot': 562,
 'bother': 563,
 'bothered': 564,
 'bothersome': 565,
 'bottom': 566,
 'bottons': 567,
 'boucle': 568,
 'bough': 569,
 'bounce': 570,
 'bouncy': 571,
 'bow': 572,
 'box': 573,
 'boxier': 574,
 'boxiness': 575,
 'boxing': 576,
 'boxy': 577,
 'boy': 578,
 'boyfriend': 579,
 'boyish': 580,
 'boyleg': 581,
 'bra': 582,
 'bracelet': 583,
 'braided': 584,
 'brainer': 585,
 'braless': 586,
 'bralette': 587,
 'bralettes': 588,
 'branch': 589,
 'brand': 590,
 'brass': 591,
 'break': 592,
 'breaker': 593,
 'breaking': 594,
 'breast': 595,
 'breasted': 596,
 'breastfeeding': 597,
 'breasting': 598,
 'breath': 599,
 'breathable': 600,
 'breathe': 601,
 'breathes': 602,
 'breathing': 603,
 'breathtaking': 604,
 'breeze': 605,
 'breezy': 606,
 'breton': 607,
 'brick': 608,
 'bridal': 609,
 'bride': 610,
 'bridesmaid': 611,
 'brief': 612,
 'briefly': 613,
 'bright': 614,
 'brighten': 615,
 'brightens': 616,
 'brighter': 617,
 'brightness': 618,
 'brilliant': 619,
 'bring': 620,
 'bringing': 621,
 'brings': 622,
 'brioche': 623,
 'brisk': 624,
 'british': 625,
 'broach': 626,
 'broad': 627,
 'broaden': 628,
 'broadened': 629,
 'broader': 630,
 'brocade': 631,
 'broke': 632,
 'broken': 633,
 'bronze': 634,
 'brooklyn': 635,
 'brought': 636,
 'brown': 637,
 'brownish': 638,
 'browse': 639,
 'browsing': 640,
 'brunch': 641,
 'brunette': 642,
 'brush': 643,
 'brushed': 644,
 'brushing': 645,
 'btu': 646,
 'btw': 647,
 'bubble': 648,
 'bubbled': 649,
 'buck': 650,
 'buckle': 651,
 'buckled': 652,
 'budge': 653,
 'budget': 654,
 'bug': 655,
 'build': 656,
 'building': 657,
 'built': 658,
 'bulge': 659,
 'bulged': 660,
 'bulging': 661,
 'bulk': 662,
 'bulkier': 663,
 'bulkiness': 664,
 'bulky': 665,
 'bullet': 666,
 'bum': 667,
 'bummed': 668,
 'bummer': 669,
 'bump': 670,
 'bumped': 671,
 'bumpy': 672,
 'bun': 673,
 'bunch': 674,
 'bunched': 675,
 'bunching': 676,
 'bunchy': 677,
 'bundle': 678,
 'burger': 679,
 'burgundy': 680,
 'burlap': 681,
 'burn': 682,
 'burned': 683,
 'burnout': 684,
 'burnt': 685,
 'burst': 686,
 'bus': 687,
 'business': 688,
 'bust': 689,
 'busted': 690,
 'bustier': 691,
 'busting': 692,
 'bustline': 693,
 'busty': 694,
 'busy': 695,
 'butt': 696,
 'butter': 697,
 'butterfly': 698,
 'buttery': 699,
 'button': 700,
 'buttondown': 701,
 'buttoned': 702,
 'buttonhole': 703,
 'buttoning': 704,
 'buy': 705,
 'buyer': 706,
 'buyi': 707,
 'buying': 708,
 'byron': 709,
 'cable': 710,
 'cactus': 711,
 'cafe': 712,
 'caftan': 713,
 'cage': 714,
 'cake': 715,
 'cal': 716,
 'calf': 717,
 'cali': 718,
 'california': 719,
 'call': 720,
 'called': 721,
 'calling': 722,
 'cam': 723,
 'camel': 724,
 'camera': 725,
 'cami': 726,
 'camis': 727,
 'camisol': 728,
 'camisole': 729,
 'camo': 730,
 'camouflage': 731,
 'camouflaging': 732,
 'camp': 733,
 'campus': 734,
 'cancel': 735,
 'cancelled': 736,
 'cancer': 737,
 'canvas': 738,
 'cap': 739,
 'cape': 740,
 'capped': 741,
 'capri': 742,
 'capsule': 743,
 'capture': 744,
 'car': 745,
 'caramel': 746,
 'carbon': 747,
 'card': 748,
 'cardi': 749,
 'cardigan': 750,
 'cardio': 751,
 'cardis': 752,
 'care': 753,
 'carefree': 754,
 'careful': 755,
 'carefully': 756,
 'cargo': 757,
 'caribbean': 758,
 'carissima': 759,
 'carpet': 760,
 'carried': 761,
 'carry': 762,
 'carrying': 763,
 'cart': 764,
 'cartonnier': 765,
 'cartoon': 766,
 'cartoonish': 767,
 'cascade': 768,
 'case': 769,
 'cash': 770,
 'cashier': 771,
 'cashmere': 772,
 'casing': 773,
 'casu': 774,
 'casual': 775,
 'casually': 776,
 'cat': 777,
 'catalog': 778,
 'catalogue': 779,
 'catch': 780,
 'catcher': 781,
 'catching': 782,
 'catchy': 783,
 'categorized': 784,
 'category': 785,
 'caught': 786,
 'causal': 787,
 'caused': 788,
 'causing': 789,
 'caution': 790,
 'cautious': 791,
 'cave': 792,
 'caveat': 793,
 'caved': 794,
 'cease': 795,
 'cedar': 796,
 'cehst': 797,
 'celadon': 798,
 'celebrate': 799,
 'celebration': 800,
 'cell': 801,
 'cellophane': 802,
 'cellulite': 803,
 'cent': 804,
 'center': 805,
 'centered': 806,
 'ceremony': 807,
 'chain': 808,
 'chair': 809,
 'challenge': 810,
 'challenged': 811,
 'challenging': 812,
 'chambray': 813,
 'chameleon': 814,
 'champagne': 815,
 'champion': 816,
 'chance': 817,
 'chanel': 818,
 'change': 819,
 'changed': 820,
 'changing': 821,
 'character': 822,
 'characteristic': 823,
 'charcoal': 824,
 'charge': 825,
 'charging': 826,
 'charisma': 827,
 'charity': 828,
 'charleston': 829,
 'charlie': 830,
 'charlies': 831,
 'charm': 832,
 'charming': 833,
 'chart': 834,
 'chartreuse': 835,
 'chase': 836,
 'chasing': 837,
 'cheap': 838,
 'cheapens': 839,
 'cheaper': 840,
 'cheaply': 841,
 'check': 842,
 'checked': 843,
 'checkered': 844,
 'checking': 845,
 'checkout': 846,
 'cheek': 847,
 'cheekier': 848,
 'cheeky': 849,
 'cheerful': 850,
 'cheery': 851,
 'cheese': 852,
 'cheesecloth': 853,
 'chemical': 854,
 'chemise': 855,
 'cherry': 856,
 'chest': 857,
 'chested': 858,
 'chesty': 859,
 'chevron': 860,
 'chic': 861,
 'chicago': 862,
 'chiffon': 863,
 'child': 864,
 'childhood': 865,
 'childish': 866,
 'chill': 867,
 'chiller': 868,
 'chillier': 869,
 'chilly': 870,
 'chin': 871,
 'china': 872,
 'chino': 873,
 'chocolate': 874,
 'choice': 875,
 'choke': 876,
 'choker': 877,
 'choking': 878,
 'choose': 879,
 'choosing': 880,
 'chopped': 881,
 'chore': 882,
 'chose': 883,
 'chosen': 884,
 'christmas': 885,
 'chrolox': 886,
 'chub': 887,
 'chubby': 888,
 'chuck': 889,
 'chuckle': 890,
 'chuckled': 891,
 'chunk': 892,
 'chunkiness': 893,
 'chunky': 894,
 'church': 895,
 'cigarette': 896,
 'cinch': 897,
 'cinched': 898,
 'cinching': 899,
 'circa': 900,
 'circle': 901,
 'circulation': 902,
 'circumference': 903,
 'circus': 904,
 'citizen': 905,
 'city': 906,
 'claim': 907,
 'claimed': 908,
 'clashed': 909,
 'clasp': 910,
 'class': 911,
 'classic': 912,
 'classical': 913,
 'classier': 914,
 'classy': 915,
 'claw': 916,
 'clay': 917,
 'cld': 918,
 'clean': 919,
 'cleaned': 920,
 'cleaner': 921,
 'cleaning': 922,
 'clear': 923,
 'clearance': 924,
 'cleavage': 925,
 'clerk': 926,
 'clever': 927,
 'cleverly': 928,
 'clicked': 929,
 'client': 930,
 'climate': 931,
 'climbing': 932,
 'cling': 933,
 'clinged': 934,
 'clingier': 935,
 'clinging': 936,
 'clingy': 937,
 'clip': 938,
 'clipped': 939,
 'clo': 940,
 'clog': 941,
 'close': 942,
 'closed': 943,
 'closely': 944,
 'closer': 945,
 'closest': 946,
 'closet': 947,
 'closeup': 948,
 'closing': 949,
 'closure': 950,
 'cloth': 951,
 'clothes': 952,
 'clothing': 953,
 'cloud': 954,
 'cloudy': 955,
 'clown': 956,
 'clownish': 957,
 'club': 958,
 'clump': 959,
 'clung': 960,
 'clunky': 961,
 'clutch': 962,
 'coal': 963,
 'coarse': 964,
 'coast': 965,
 'coat': 966,
 'coated': 967,
 'cobalt': 968,
 'cocktail': 969,
 'cocoon': 970,
 'code': 971,
 'coffee': 972,
 'cognac': 973,
 'coh': 974,
 'cohesive': 975,
 'col': 976,
 'cold': 977,
 'colder': 978,
 'coldest': 979,
 'collage': 980,
 'collar': 981,
 'collarbone': 982,
 'collared': 983,
 'colleague': 984,
 'collect': 985,
 'collected': 986,
 'collecting': 987,
 'collection': 988,
 'college': 989,
 'colo': 990,
 'color': 991,
 'colorado': 992,
 'coloration': 993,
 'colorblock': 994,
 'colorblocked': 995,
 'colored': 996,
 'colorfast': 997,
 'colorful': 998,
 'coloring': 999,
 ...}

## 4. Export Vocabulary & Processed Dataset <a id="export-vocabulary-processed-dataset"></a>
Save the requested information as per specification.
- vocab.txt

In [ ]:
# Saving vocab.txt (as word:idx) and processed.csv freezes the artifacts used for modeling
with open("vocab.txt", "w", encoding="utf-8") as f:
    for word, idx in vocab_dict.items():
        f.write(f"{word}:{idx}\n")

df.to_csv("processed.csv", index=False)