# Assignment 2: Milestone I Natural Language Processing
## Task 1. Basic Text Pre-processing
#### Student Name: XXXX XXXX
#### Student ID: 000000


Environment: Python 3 and Jupyter notebook

Libraries used: please include all the libraries you used in your assignment, e.g.,:
* pandas
* re
* numpy

## Introduction
You should give a brief information of this assessment task here.

<span style="color: red"> Note that this is a sample notebook only. You will need to fill in the proper markdown and code blocks. You might also want to make necessary changes to the structure to meet your own needs. Note also that any generic comments written in this notebook are to be removed and replace with your own words.</span>

## Importing libraries

In [6]:
# Code to import libraries as you need in this assessment, e.g.,
import numpy as np
import matplotlib.pyplot as plt
import os
import re
import zipfile
from textblob import TextBlob
from collections import Counter
from pathlib import Path
from nltk.tokenize import RegexpTokenizer
from nltk.stem import PorterStemmer, WordNetLemmatizer
from spellchecker import SpellChecker
from nltk.corpus import wordnet
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
from collections import Counter
import pandas as pd

[nltk_data] Downloading package punkt to /Users/vongoc/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/vongoc/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/vongoc/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /Users/vongoc/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/vongoc/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/vongoc/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

### 1.1 Examining and loading data
- Examine the data and explain your findings
- Load the data into proper data structures and get it ready for processing.

In [7]:
# Code to inspect the provided data file...
current_directory = Path(__file__).parent if '__file__' in locals() else Path.cwd()
print(f"Current directory: {current_directory}")
with zipfile.ZipFile(f"{current_directory}/data.zip", 'r') as zip_ref:
    zip_ref.extractall(current_directory)

Current directory: /Users/vongoc/Documents/GitHub/ASM3-APDS/data

FileNotFoundError: [Errno 2] No such file or directory: '/Users/vongoc/Documents/GitHub/ASM3-APDS/data/data.zip'

In [8]:
df = pd.read_csv('assignment3.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19662 entries, 0 to 19661
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Clothing ID              19662 non-null  int64
 1   Age                      19662 non-null  int64
 2   Title                    19662 non-null  object
 3   Review Text              19662 non-null  object
 4   Rating                   19662 non-null  int64
 5   Recommended IND          19662 non-null  int64
 6   Positive Feedback Count  19662 non-null  int64
 7   Division Name            19662 non-null  object
 8   Department Name          19662 non-null  object
 9   Class Name               19662 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.5+ MB

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
1,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
2,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses
3,1080,49,Not for the very petite,"I love tracy reese dresses, but this one is no...",2,0,4,General,Dresses,Dresses
4,858,39,Cagrcoal shimmer fun,I aded this in my basket at hte last mintue to...,5,1,1,General Petite,Tops,Knits

### 1.2 Pre-processing data
Perform the required text pre-processing steps.

...... Sections and code blocks on basic text pre-processing


<span style="color: red"> You might have complex notebook structure in this section, please feel free to create your own notebook structure. </span>

In [9]:
# 2/3/4. Tokenizing clothing review

# define tokenizer
tokenizer = RegexpTokenizer(r"[a-zA-Z]+(?:[-'][a-zA-Z]+)?")

# Tokenize the review text + lowercasing and removing words with length < 2
df["tokens"] = (
    df["Review Text"]
      .fillna("") # replace NaN with empty string
      .astype(str)
      .apply(lambda text: [token.lower() for token in tokenizer.tokenize(text) if len(token) > 1])
)

# quick spot-checks (delete when done)
print(df["tokens"].head(3).tolist())
assert isinstance(df["tokens"].iloc[0], list)

[['had', 'such', 'high', 'hopes', 'for', 'this', 'dress', 'and', 'really', 'wanted', 'it', 'to', 'work', 'for', 'me', 'initially', 'ordered', 'the', 'petite', 'small', 'my', 'usual', 'size', 'but', 'found', 'this', 'to', 'be', 'outrageously', 'small', 'so', 'small', 'in', 'fact', 'that', 'could', 'not', 'zip', 'it', 'up', 'reordered', 'it', 'in', 'petite', 'medium', 'which', 'was', 'just', 'ok', 'overall', 'the', 'top', 'half', 'was', 'comfortable', 'and', 'fit', 'nicely', 'but', 'the', 'bottom', 'half', 'had', 'very', 'tight', 'under', 'layer', 'and', 'several', 'somewhat', 'cheap', 'net', 'over', 'layers', 'imo', 'major', 'design', 'flaw', 'was', 'the', 'net', 'over', 'layer', 'sewn', 'directly', 'into', 'the', 'zipper', 'it'], ['love', 'love', 'love', 'this', 'jumpsuit', "it's", 'fun', 'flirty', 'and', 'fabulous', 'every', 'time', 'wear', 'it', 'get', 'nothing', 'but', 'great', 'compliments'], ['this', 'shirt', 'is', 'very', 'flattering', 'to', 'all', 'due', 'to', 'the', 'adjustable', 'front', 'tie', 'it', 'is', 'the', 'perfect', 'length', 'to', 'wear', 'with', 'leggings', 'and', 'it', 'is', 'sleeveless', 'so', 'it', 'pairs', 'well', 'with', 'any', 'cardigan', 'love', 'this', 'shirt']]

In [10]:
def correct_text(text):
    return str(TextBlob(text).correct())

def correct_tokens(token_list):
    corrected_tokens = []
    for token in token_list:
        corrected_token = correct_text(token)
        corrected_tokens.append(corrected_token)
    return corrected_tokens

df["tokens"] = df["tokens"].apply(correct_tokens)

In [11]:
lemmatizer = WordNetLemmatizer()
spell = SpellChecker()

# -------------------------------
# Clean tokens
# -------------------------------
def clean_tokens(tokens):
    if not isinstance(tokens, list):
        return []
    return [str(t).lower() for t in tokens if t is not None]

# -------------------------------
# Spell checking
# -------------------------------
def correct_tokens(tokens):
    corrected = []
    for word in tokens:
        if word in spell.unknown([word]):
            suggestion = spell.correction(word)
            corrected.append(suggestion if suggestion is not None else word)
        else:
            corrected.append(word)
    return corrected


# -------------------------------
# Apply pipeline
# -------------------------------
df["tokens"] = df["tokens"].apply(clean_tokens)
df["tokens"] = df["tokens"].apply(correct_tokens)

In [12]:
# 5. Remove stopwords using the provided stop words list (i.e., stopwords_en.txt). It is located inside the same downloaded folder. 
# Find file stopwords in data
stop_path = Path("stopwords_en.txt")

# Load stopwords
with open(stop_path, "r", encoding="utf-8") as f:
    stop_words = {line.strip() for line in f if line.strip()}

print(f"[Q5] Loaded {len(stop_words)} stopwords from {stop_path}")

# Remove stopwords (Compare lowercase)
def remove_stopwords(tokens, stopset):
    return [t for t in tokens if t.lower() not in stopset]

df["tokens"] = df["tokens"].apply(remove_stopwords, stopset=stop_words)

# Print to check
print(df[["tokens"]].head(2))

[Q5] Loaded 570 stopwords from stopwords_en.txt
                                              tokens
0  [high, hopes, dress, wanted, work, initially, ...
1  [love, love, love, jumpsuit, fun, flirt, fabul...

In [13]:
# 6. Remove the word that appears only once in the document collection, based on term frequency.
term_freq = pd.Series(np.concatenate(df["tokens"].values)).value_counts()
 
df["tokens"] = df["tokens"].apply(lambda tokens: [token for token in tokens if term_freq[token] > 1])

# Double check
term_freq = pd.Series(np.concatenate(df["tokens"].values)).value_counts()
term_freq

dress        9531
size         7876
love         7735
fit          6585
top          6548
             ...
sins            2
semblance       2
banking         2
utter           2
crossway        2
Name: count, Length: 6370, dtype: int64

In [14]:
# 7. Remove the top 20 most frequent words based on document frequency. 
# Count document frequency (each word counts only once per doc)
doc_freq = Counter()
for tokens in df["tokens"]:
    unique_tokens = set(tokens)
    doc_freq.update(unique_tokens)

# Get the top 20 most frequent words
top_20_words = {word for word, _ in doc_freq.most_common(20)}
print("Top 20 frequent words:", top_20_words)

# Remove them from each token list
df["tokens"] = df["tokens"].apply(
    lambda tokens: [w for w in tokens if w not in top_20_words]
)

Top 20 frequent words: {'top', 'fabric', 'comfortable', 'flattering', 'love', 'soft', 'nice', 'dress', 'small', 'fits', 'wear', 'size', 'perfect', 'cut', 'fit', 'great', 'bought', 'color', 'ordered', 'back'}

In [15]:
lemmatizer = WordNetLemmatizer()
df["tokens"] = [[lemmatizer.lemmatize(w) for w in review] for review in df["tokens"].tolist()]

In [16]:
def clean_vocab_token(token):
    token = token.lower().strip()
    if re.fullmatch(r"[a-z0-9]+", token) and len(token) > 2:
        return token
    return None

cleaned_tokens = df["tokens"].apply(lambda tokens: [clean_vocab_token(t) for t in tokens if t is not None])
df["tokens"] = cleaned_tokens.apply(lambda tokens: [t for t in tokens if t is not None])

In [17]:
df[["tokens"]].head(50)

                                               tokens
0   [high, hope, wanted, work, initially, petite, ...
1   [jumpsuit, fun, flirt, fabulous, time, complim...
2   [shirt, due, adjustable, front, tie, length, l...
3   [trace, goose, dress, petite, foot, tall, bran...
4   [added, basket, minute, person, store, pick, d...
5   [carbon, store, pick, ton, stuff, pair, skirt,...
6   [run, snug, bust, feminine, usual, retailer, f...
7   [petite, make, length, long, typically, regula...
8   [run, nipper, area, run, typically, tight, mat...
9   [find, radiant, review, written, navvy, shippe...
10  [black, larkspur, mid, bother, lining, skirt, ...
11  [choice, holiday, gathering, length, knee, con...
12  [package, wanted, badly, put, hourglass, figur...
13  [material, leg, opening, large, length, hit, a...
14  [chance, louse, glad, crazy, louse, photograph...
15  [super, copy, coat, work, cold, dry, day, good...
16  [feel, eve, chester, form, fitting, steamed, l...
17  [product, petite, petite, regular, long, tailo...
18  [upset, price, thought, embroidered, print, op...
19  [plover, side, nipper, purchased, knew, side, ...
20  [high, waisted, good, length, height, feel, ch...
21  [shirt, shirt, slip, legging, slip, wore, tie,...
22  [loved, material, long, purchased, large, medi...
23  [waiting, sweeter, coat, ship, week, excited, ...
24  [color, expected, dark, blue, vagrant, find, t...
25          [shirt, compliment, hesitate, buy, shirt]
26  [sweeter, classic, balance, quickly, beautiful...
27  [part, online, person, outer, stripe, brighter...
28             [part, person, downside, dry, cleaned]
29  [month, ago, finally, order, huge, disappointm...
30  [neat, super, tall, long, length, added, bonus...
31                                      [store, whim]
32  [medium, mon, gorgeous, beautifully, draped, w...
33  [porch, plaid, check, design, color, street, c...
34  [thermal, naturally, expect, super, sheer, she...
35  [today, local, retailer, bad, picture, online,...
36  [item, online, model, looked, loose, mine, bit...
37            [sweeter, fall, room, warm, super, pip]
38  [embroidery, collar, big, beautiful, unique, r...
39  [transition, easily, summer, fall, print, stor...
40  [absolutely, big, favorite, retailer, purchase...
41  [shirt, unusual, symmetrical, seat, appears, f...
42  [armhole, bit, oversized, older, woman, pick, ...
43  [adorable, find, extremely, buy, print, femini...
44  [tank, loved, ruffle, played, front, good, ret...
45  [brunette, provide, support, binding, tight, n...
46  [simply, beautiful, stunning, figure, wait, wo...
47  [tag, sewn, long, huge, itchy, thread, left, p...
48  [recently, sale, forever, list, happy, long, t...
49  [shirt, light, weight, lovely, flora, color, s...

In [18]:
from collections import Counter

# Flatten all tokens
all_tokens = [t for tokens in df["tokens"] for t in tokens]


token_counts = Counter(all_tokens)
print(token_counts)

# Sort vocab
unique_vocab = sorted(all_tokens)
vocab_dict = {word: idx for idx, word in enumerate(unique_vocab)}

Counter({'shirt': 2751, 'bit': 2595, 'material': 2506, 'large': 2504, 'beautiful': 2502, 'part': 2425, 'length': 2387, 'jean': 2334, 'petite': 2304, 'work': 2293, 'run': 2266, 'sweeter': 2257, 'long': 2158, 'short': 2156, 'color': 2133, 'waist': 2123, 'medium': 2053, 'skirt': 2014, 'quality': 1970, 'pretty': 1953, 'make': 1894, 'retailer': 1892, 'feel': 1872, 'store': 1859, 'sleeve': 1827, 'good': 1750, 'body': 1684, 'made': 1659, 'big': 1646, 'black': 1601, 'style': 1551, 'review': 1527, 'online': 1504, 'true': 1501, 'summer': 1489, 'super': 1471, 'design': 1394, 'wearing': 1389, 'arm': 1377, 'purchased': 1370, 'white': 1327, 'perfectly': 1301, 'fall': 1300, 'shoulder': 1293, 'tight': 1287, 'price': 1266, 'time': 1249, 'model': 1249, 'bottom': 1239, 'sale': 1230, 'loose': 1222, 'front': 1201, 'blue': 1185, 'detail': 1184, 'looked': 1179, 'jacket': 1177, 'side': 1140, 'person': 1130, 'loved': 1125, 'piece': 1099, 'regular': 1051, 'chest': 1041, 'stretch': 1041, 'picture': 1037, 'worn': 1017, 'day': 1011, 'shape': 1009, 'hip': 1000, 'pattern': 1000, 'lot': 998, 'pair': 991, 'photo': 988, 'thought': 987, 'light': 961, 'high': 957, 'button': 957, 'wanted': 953, 'lovely': 933, 'gorgeous': 932, 'bust': 922, 'thin': 914, 'compliment': 911, 'casual': 908, 'recommend': 907, 'print': 903, 'flow': 888, 'louse': 873, 'top': 871, 'find': 865, 'found': 848, 'wore': 847, 'bar': 842, 'thing': 810, 'weight': 795, 'usual': 794, 'hit': 792, 'dress': 789, 'buy': 785, 'order': 781, 'received': 776, 'longer': 749, 'red': 732, 'room': 728, 'nicely': 719, 'slightly': 716, 'legging': 699, 'absolutely': 699, 'return': 696, 'fitted': 696, 'felt': 695, 'green': 688, 'neck': 679, 'underneath': 675, 'area': 675, 'unique': 666, 'pocket': 658, 'tank': 652, 'happy': 649, 'boot': 646, 'easy': 643, 'fun': 636, 'wide': 636, 'lace': 633, 'seizing': 630, 'knee': 625, 'purchase': 622, 'extra': 616, 'show': 607, 'size': 606, 'year': 594, 'warm': 594, 'fine': 584, 'leg': 570, 'smaller': 569, 'sheer': 569, 'dressed': 569, 'huge': 553, 'tall': 549, 'shorter': 549, 'reference': 544, 'worth': 543, 'glad': 541, 'give': 540, 'low': 540, 'put': 539, 'full': 537, 'add': 530, 'problem': 529, 'decided': 524, 'line': 524, 'layer': 523, 'inch': 522, 'spring': 522, 'skinny': 518, 'navy': 517, 'wait': 512, 'larger': 509, 'denis': 508, 'winter': 506, 'disappointed': 501, 'favorite': 497, 'versatile': 497, 'adorable': 496, 'decline': 496, 'figure': 494, 'issue': 490, 'sized': 481, 'thick': 478, 'easily': 473, 'lightweight': 471, 'kind': 464, 'returned': 463, 'coat': 463, 'pink': 463, 'snug': 457, 'cotton': 457, 'slip': 455, 'grey': 450, 'wash': 449, 'tunic': 445, 'hem': 440, 'amazing': 440, 'dark': 435, 'heavy': 435, 'normal': 434, 'swing': 432, 'feminine': 429, 'hang': 429, 'flat': 427, 'pictured': 423, 'knit': 418, 'hole': 415, 'frame': 406, 'item': 405, 'belt': 405, 'type': 404, 'cardiac': 403, 'strap': 400, 'tie': 398, 'lining': 398, 'reviewed': 397, 'curly': 395, 'expected': 393, 'torso': 393, 'embroidery': 390, 'typically': 385, 'beautifully': 385, 'fitting': 382, 'extremely': 380, 'lined': 378, 'excited': 378, 'returning': 376, 'washed': 372, 'ran': 368, 'highly': 368, 'skin': 367, 'draped': 364, 'today': 362, 'shown': 352, 'bad': 348, 'suit': 347, 'heel': 345, 'sold': 344, 'ended': 344, 'cool': 341, 'season': 335, 'weather': 333, 'needed': 332, 'swimming': 328, 'gray': 326, 'vest': 324, 'stylish': 321, 'arrived': 321, 'nipper': 320, 'busy': 319, 'fell': 319, 'local': 319, 'flare': 316, 'ankle': 316, 'agree': 316, 'pull': 315, 'orange': 314, 'hard': 314, 'brand': 310, 'hoping': 310, 'wardrobe': 307, 'place': 306, 'due': 304, 'hope': 301, 'copy': 300, 'sadly': 295, 'staple': 295, 'hot': 295, 'cheap': 294, 'silk': 293, 'keeping': 293, 'night': 291, 'girl': 290, 'slim': 290, 'classic': 287, 'touch': 287, 'open': 287, 'cover': 287, 'plan': 284, 'texture': 283, 'water': 281, 'surprised': 281, 'dry': 279, 'vagrant': 275, 'wonderful': 273, 'micro': 273, 'version': 273, 'baggy': 269, 'pound': 269, 'ordering': 268, 'fact': 267, 'delicate': 266, 'thigh': 265, 'based': 264, 'straight': 263, 'yellow': 263, 'grape': 262, 'bright': 260, 'woman': 259, 'stunning': 259, 'wedding': 259, 'end': 257, 'month': 257, 'cropped': 255, 'simple': 253, 'itchy': 253, 'worked': 252, 'edge': 250, 'lay': 249, 'oversized': 248, 'haired': 242, 'bigger': 240, 'immediately': 240, 'right': 239, 'outfit': 238, 'mentioned': 237, 'jumpsuit': 236, 'making': 236, 'pick': 235, 'tiny': 234, 'clothes': 233, 'previous': 232, 'scandal': 232, 'elastic': 231, 'special': 230, 'hold': 230, 'buying': 230, 'mine': 227, 'ivory': 227, 'cold': 226, 'week': 225, 'totally': 225, 'curve': 225, 'wrinkle': 225, 'mind': 224, 'lower': 223, 'band': 223, 'completely': 222, 'reason': 221, 'hide': 220, 'athletic': 220, 'collar': 219, 'broad': 219, 'higher': 218, 'armhole': 217, 'eye': 216, 'cootie': 216, 'weird': 213, 'slit': 213, 'wool': 212, 'knew': 211, 'read': 211, 'neutral': 211, 'complaint': 210, 'star': 209, 'hourglass': 208, 'people': 208, 'laying': 207, 'finally': 207, 'similar': 207, 'cling': 207, 'cream': 206, 'chin': 205, 'pleased': 204, 'stiff': 204, 'worried': 204, 'structure': 203, 'thinking': 202, 'wrong': 201, 'amount': 201, 'incredibly': 201, 'spot': 200, 'odd': 200, 'point': 200, 'interesting': 199, 'substantial': 198, 'house': 197, 'prefer': 197, 'sex': 197, 'awesome': 196, 'seat': 194, 'class': 194, 'mid': 193, 'brown': 193, 'upper': 193, 'inside': 193, 'deep': 193, 'ruffle': 192, 'party': 191, 'bulky': 190, 'linen': 190, 'rich': 190, 'close': 190, 'hand': 190, 'clothing': 189, 'basic': 188, 'half': 187, 'subtle': 187, 'closet': 187, 'throw': 187, 'couple': 186, 'home': 186, 'thread': 185, 'mail': 185, 'depending': 185, 'addition': 185, 'waisted': 184, 'washing': 184, 'tailor': 183, 'appears': 183, 'stripe': 183, 'elegant': 183, 'left': 182, 'flower': 182, 'cup': 181, 'product': 181, 'expect': 181, 'stay': 180, 'gave': 180, 'weekend': 177, 'option': 176, 'rude': 176, 'septum': 175, 'justice': 175, 'detailing': 175, 'thicker': 174, 'purple': 174, 'case': 173, 'idea': 172, 'forward': 171, 'lady': 171, 'flora': 170, 'bodice': 169, 'baby': 168, 'sad': 168, 'fan': 167, 'sort': 166, 'build': 166, 'form': 165, 'mummy': 165, 'paternity': 165, 'tag': 164, 'sweatshirt': 164, 'fairly': 163, 'added': 162, 'office': 162, 'necklace': 162, 'exchange': 161, 'ton': 160, 'deal': 160, 'opinion': 159, 'plea': 159, 'taller': 159, 'poor': 158, 'real': 158, 'imagine': 157, 'blazed': 157, 'hung': 157, 'narrow': 157, 'slight': 156, 'feeling': 156, 'motif': 156, 'darker': 155, 'expecting': 155, 'middle': 155, 'rise': 154, 'gold': 154, 'occasion': 153, 'belly': 153, 'fantastic': 153, 'pulled': 153, 'heavier': 153, 'colored': 152, 'butt': 152, 'live': 151, 'noticed': 151, 'fabulous': 150, 'awkward': 150, 'past': 149, 'outer': 149, 'barely': 148, 'cuff': 147, 'typical': 146, 'leather': 145, 'waistband': 145, 'zip': 144, 'showing': 144, 'transition': 144, 'coming': 144, 'scratch': 144, 'coverage': 144, 'tent': 144, 'seam': 144, 'reading': 143, 'holiday': 141, 'romper': 141, 'meant': 141, 'foot': 140, 'dinner': 140, 'bag': 140, 'tucked': 139, 'match': 138, 'generally': 138, 'stitching': 138, 'comfort': 137, 'beach': 137, 'sewn': 136, 'strange': 136, 'event': 136, 'shade': 136, 'portion': 135, 'rest': 135, 'simply': 134, 'forgiving': 134, 'running': 133, 'lighter': 133, 'excellent': 133, 'husband': 133, 'height': 132, 'chance': 132, 'pillow': 132, 'ago': 131, 'stand': 131, 'evening': 131, 'wider': 130, 'grumpy': 130, 'hour': 128, 'slender': 128, 'expensive': 128, 'pregnant': 127, 'difficult': 127, 'caught': 127, 'solid': 126, 'airy': 126, 'note': 125, 'dot': 124, 'stock': 123, 'finding': 123, 'camisole': 122, 'uncomfortable': 122, 'silhouette': 122, 'shoe': 122, 'care': 121, 'plenty': 121, 'funny': 119, 'shrink': 119, 'coral': 119, 'glove': 119, 'description': 118, 'overlay': 118, 'relaxed': 118, 'money': 118, 'flaw': 117, 'chester': 117, 'aline': 117, 'move': 117, 'stomach': 117, 'clean': 116, 'guess': 116, 'hanging': 116, 'opening': 115, 'tone': 115, 'cooper': 115, 'maxim': 115, 'trend': 114, 'surprise': 114, 'dressing': 114, 'daughter': 113, 'stick': 113, 'keeper': 113, 'garment': 112, 'average': 112, 'quickly': 112, 'prettier': 112, 'purchasing': 112, 'natural': 111, 'polyester': 111, 'plain': 110, 'life': 110, 'beige': 110, 'feature': 110, 'snap': 109, 'combination': 109, 'beading': 109, 'yesterday': 109, 'recently': 108, 'shapeless': 108, 'wrap': 108, 'mix': 107, 'pencil': 107, 'plaid': 107, 'originally': 107, 'send': 107, 'strike': 107, 'minute': 106, 'sit': 106, 'adore': 106, 'webster': 106, 'afraid': 106, 'receive': 105, 'floppy': 105, 'pas': 105, 'danger': 105, 'pale': 104, 'porch': 104, 'pay': 103, 'tend': 103, 'tree': 103, 'section': 102, 'sack': 102, 'flowing': 102, 'head': 102, 'package': 101, 'help': 100, 'disappointing': 100, 'way': 100, 'turtleneck': 99, 'stretched': 99, 'stated': 99, 'set': 99, 'covered': 99, 'sang': 98, 'start': 98, 'dusted': 98, 'taking': 98, 'flatter': 97, 'friend': 97, 'scarf': 97, 'bell': 97, 'movement': 96, 'moss': 96, 'shaped': 95, 'machine': 95, 'supposed': 95, 'bow': 95, 'wish': 94, 'tighter': 94, 'picked': 94, 'designed': 94, 'sweet': 94, 'choice': 93, 'crazy': 93, 'embroidered': 93, 'mean': 93, 'comment': 93, 'construction': 93, 'effect': 93, 'rolled': 93, 'hate': 93, 'fly': 92, 'chose': 92, 'velvet': 92, 'thrilled': 92, 'trim': 92, 'crop': 91, 'warmer': 91, 'unlike': 91, 'negative': 91, 'noted': 91, 'romantic': 91, 'attractive': 91, 'pulling': 90, 'unusual': 90, 'designer': 90, 'accentuated': 90, 'resistant': 90, 'difference': 90, 'literally': 89, 'paid': 89, 'shrunk': 89, 'fully': 89, 'comb': 89, 'tuck': 89, 'whim': 88, 'beauty': 88, 'whistling': 88, 'muscular': 88, 'carry': 87, 'everyday': 87, 'comfortably': 87, 'round': 87, 'jewel': 86, 'hoped': 86, 'trouser': 86, 'mute': 86, 'suggest': 86, 'roll': 85, 'support': 85, 'tape': 85, 'bunch': 85, 'dream': 85, 'disappoint': 85, 'panel': 85, 'boyfriend': 85, 'surprisingly': 84, 'notice': 84, 'trip': 84, 'bump': 84, 'careful': 83, 'wear': 83, 'fence': 83, 'pleasantly': 83, 'rose': 83, 'wine': 83, 'understand': 83, 'attention': 83, 'turquoise': 83, 'date': 83, 'walk': 82, 'attached': 82, 'weigh': 82, 'olive': 82, 'compared': 82, 'multiple': 82, 'exception': 82, 'nicer': 81, 'vice': 81, 'sending': 81, 'bother': 80, 'fix': 80, 'overwhelming': 80, 'panama': 80, 'winner': 80, 'lost': 80, 'statement': 80, 'calf': 80, 'jersey': 80, 'shot': 80, 'lip': 80, 'early': 80, 'armpit': 80, 'adjustable': 79, 'terrible': 79, 'gap': 79, 'vantage': 79, 'entire': 79, 'wonderfully': 79, 'lavender': 79, 'initially': 78, 'pear': 78, 'thinner': 78, 'bulk': 78, 'pop': 78, 'sleepless': 77, 'christmas': 77, 'breast': 77, 'adding': 77, 'cord': 77, 'worry': 77, 'brighter': 76, 'mon': 76, 'interest': 76, 'change': 76, 'hook': 76, 'bathing': 76, 'giving': 76, 'errand': 76, 'rack': 76, 'drawn': 75, 'hair': 75, 'liking': 75, 'faded': 75, 'showed': 75, 'trouble': 75, 'double': 75, 'shopping': 75, 'swimsuit': 75, 'awful': 75, 'flair': 74, 'hemmed': 74, 'blend': 74, 'wrinkled': 74, 'leave': 74, 'decide': 73, 'sits': 73, 'cloth': 73, 'concerned': 73, 'flared': 73, 'swimmer': 72, 'sturdy': 72, 'tied': 72, 'plunge': 72, 'honestly': 72, 'waiting': 71, 'altered': 71, 'turned': 71, 'cleavage': 71, 'breezy': 71, 'closure': 71, 'number': 71, 'center': 71, 'dresser': 70, 'check': 70, 'stone': 70, 'revealing': 70, 'bill': 70, 'contrast': 70, 'gift': 69, 'falling': 69, 'stuck': 68, 'rib': 68, 'wrist': 68, 'shipping': 68, 'turn': 67, 'happen': 67, 'discount': 67, 'metallic': 67, 'modest': 67, 'realize': 67, 'moment': 67, 'stop': 67, 'helene': 67, 'volume': 67, 'preferred': 67, 'standard': 67, 'silver': 67, 'proportion': 66, 'lose': 66, 'owned': 66, 'vacation': 66, 'catalogue': 66, 'miss': 66, 'travel': 66, 'disappointment': 65, 'bring': 65, 'striped': 65, 'realized': 65, 'matter': 65, 'width': 65, 'smooth': 65, 'tireless': 65, 'crutch': 65, 'cashier': 65, 'weave': 65, 'sparkle': 65, 'perfection': 65, 'opened': 64, 'bonus': 64, 'symmetrical': 64, 'washable': 64, 'summed': 64, 'age': 64, 'image': 64, 'properly': 64, 'burgundy': 64, 'ridiculous': 64, 'pro': 64, 'gathered': 64, 'flirt': 63, 'styled': 63, 'figured': 63, 'fold': 63, 'regret': 63, 'modern': 63, 'putting': 63, 'accessory': 63, 'buttoned': 63, 'free': 63, 'twist': 63, 'plover': 62, 'call': 62, 'recommended': 62, 'amp': 62, 'lounge': 62, 'exchanged': 62, 'concern': 61, 'measurement': 61, 'dryer': 61, 'page': 61, 'mother': 61, 'shift': 61, 'watching': 61, 'personally': 61, 'considered': 61, 'complement': 61, 'taste': 61, 'additional': 61, 'actual': 61, 'county': 61, 'mention': 60, 'label': 60, 'walked': 60, 'hood': 60, 'sloughy': 60, 'waited': 60, 'working': 60, 'fuller': 60, 'impressed': 60, 'birthday': 60, 'instantly': 60, 'downside': 59, 'eying': 59, 'grab': 59, 'exchanging': 59, 'oddly': 59, 'happened': 59, 'placement': 59, 'require': 59, 'simon': 59, 'business': 58, 'generous': 58, 'basically': 58, 'closed': 58, 'shame': 58, 'cost': 58, 'flap': 58, 'bearable': 58, 'background': 58, 'level': 58, 'warmth': 57, 'card': 57, 'plum': 57, 'engaged': 57, 'floor': 57, 'holding': 57, 'filling': 57, 'closer': 57, 'post': 57, 'grabbed': 57, 'darling': 57, 'offered': 57, 'happier': 56, 'sleep': 56, 'cart': 56, 'started': 56, 'avoid': 56, 'voluminous': 56, 'breathable': 56, 'take': 56, 'gaping': 56, 'softness': 55, 'expectation': 55, 'helped': 55, 'casually': 55, 'striking': 55, 'rear': 55, 'united': 55, 'late': 55, 'positive': 54, 'planning': 54, 'ribbon': 54, 'oho': 54, 'correct': 54, 'sophisticated': 54, 'lucky': 54, 'heat': 54, 'loop': 53, 'state': 53, 'polished': 53, 'coal': 53, 'art': 53, 'mess': 53, 'glimmer': 53, 'detailed': 53, 'instruction': 53, 'lipped': 53, 'polk': 53, 'searching': 53, 'string': 53, 'mustard': 53, 'reminds': 53, 'accommodate': 53, 'air': 53, 'single': 53, 'retro': 53, 'possibly': 53, 'breaker': 53, 'meet': 53, 'crisp': 52, 'box': 52, 'visible': 52, 'accent': 52, 'softer': 52, 'inshore': 52, 'customer': 52, 'beware': 52, 'passed': 52, 'shipper': 51, 'colorful': 51, 'ride': 51, 'obsessed': 51, 'constructed': 51, 'disagree': 51, 'son': 51, 'dye': 51, 'coloring': 51, 'asked': 51, 'bead': 51, 'ensure': 51, 'fur': 51, 'chambray': 51, 'drawstring': 51, 'begging': 51, 'sitting': 51, 'built': 50, 'slack': 50, 'spend': 50, 'called': 50, 'hug': 50, 'gripped': 50, 'cross': 50, 'fringe': 50, 'alternative': 49, 'versatility': 49, 'bohemian': 49, 'site': 49, 'mixed': 49, 'exposed': 49, 'flatters': 49, 'yarn': 49, 'noticeable': 49, 'aware': 49, 'love': 49, 'professional': 49, 'loosely': 49, 'spade': 49, 'shed': 49, 'alteration': 48, 'lack': 48, 'thou': 48, 'ultimately': 48, 'smell': 48, 'job': 48, 'flannel': 48, 'elbow': 48, 'pleasing': 48, 'formal': 48, 'thickness': 48, 'drop': 48, 'choose': 48, 'began': 48, 'rarely': 48, 'penny': 48, 'badly': 47, 'scoop': 47, 'enjoy': 47, 'gas': 47, 'waste': 47, 'cage': 47, 'sock': 47, 'write': 47, 'doubt': 46, 'luxurious': 46, 'fancy': 46, 'pin': 46, 'sheen': 46, 'luck': 46, 'contest': 46, 'florida': 46, 'general': 46, 'dried': 46, 'practical': 45, 'lounging': 45, 'lean': 45, 'create': 45, 'cycle': 45, 'missing': 45, 'enormous': 45, 'droning': 45, 'robe': 45, 'held': 45, 'luckily': 45, 'rogers': 45, 'empire': 45, 'unable': 45, 'transitional': 45, 'adjust': 45, 'fast': 45, 'ideal': 45, 'formfitting': 44, 'sense': 44, 'incredible': 44, 'accurate': 44, 'colder': 44, 'boring': 44, 'hidden': 44, 'term': 44, 'range': 44, 'begin': 44, 'walking': 44, 'fair': 44, 'stopped': 43, 'rocket': 43, 'potential': 43, 'belted': 43, 'dissection': 43, 'eyelid': 43, 'rough': 43, 'pregnancy': 43, 'laid': 43, 'cardigan': 43, 'concept': 43, 'drawback': 43, 'experience': 43, 'charcoal': 42, 'conservative': 42, 'rushing': 42, 'ala': 42, 'burnt': 42, 'poorly': 42, 'wanting': 42, 'snugly': 42, 'variety': 42, 'woven': 42, 'rare': 42, 'boy': 42, 'offer': 42, 'shiny': 42, 'loving': 42, 'horrible': 42, 'nervous': 42, 'balance': 41, 'including': 41, 'fat': 41, 'gal': 41, 'ready': 41, 'ease': 41, 'split': 41, 'biggest': 41, 'iron': 41, 'fashion': 41, 'recent': 41, 'peasant': 41, 'lift': 41, 'justify': 41, 'skinned': 41, 'tricky': 41, 'variation': 41, 'tailing': 41, 'bold': 41, 'smallest': 40, 'arrive': 40, 'removed': 40, 'sky': 40, 'stain': 40, 'cuvier': 40, 'decent': 40, 'intricate': 40, 'receiving': 40, 'risk': 40, 'pill': 40, 'lump': 40, 'functional': 40, 'stitch': 40, 'paring': 40, 'mark': 40, 'terribly': 40, 'sensitive': 39, 'stitched': 39, 'face': 39, 'coverup': 39, 'fresh': 39, 'chilly': 39, 'maude': 39, 'tired': 39, 'horse': 39, 'definite': 39, 'dealing': 39, 'lookout': 39, 'friday': 39, 'morning': 39, 'main': 39, 'word': 39, 'shower': 39, 'purpose': 39, 'brass': 39, 'checked': 39, 'branch': 39, 'brought': 38, 'whimsical': 38, 'distressed': 38, 'ribbed': 38, 'ahead': 38, 'equine': 38, 'puffy': 38, 'steal': 38, 'mistake': 38, 'young': 38, 'struggle': 38, 'kiss': 38, 'halted': 38, 'required': 38, 'advice': 38, 'booty': 38, 'constantly': 38, 'pure': 38, 'result': 38, 'swede': 38, 'creates': 37, 'pinched': 37, 'con': 37, 'raw': 37, 'california': 37, 'pattered': 37, 'awhile': 37, 'mint': 37, 'punched': 37, 'worse': 37, 'earlier': 37, 'fixed': 37, 'correctly': 37, 'draping': 37, 'bone': 37, 'balloon': 37, 'space': 37, 'jumper': 37, 'transparent': 37, 'gentle': 36, 'appearance': 36, 'play': 36, 'sport': 36, 'commented': 36, 'corduroy': 36, 'shop': 36, 'impossible': 35, 'told': 35, 'sweat': 35, 'angle': 35, 'suppose': 35, 'younger': 35, 'sell': 35, 'finger': 35, 'attracted': 35, 'awkwardly': 35, 'leaving': 35, 'backside': 35, 'town': 35, 'step': 35, 'sister': 35, 'hint': 35, 'square': 35, 'swim': 35, 'effortless': 35, 'resist': 35, 'promo': 35, 'view': 35, 'gauzy': 35, 'tempted': 35, 'suggested': 35, 'steve': 35, 'cape': 35, 'thankful': 35, 'complete': 35, 'trench': 35, 'gompers': 35, 'describe': 34, 'debated': 34, 'mirror': 34, 'vivid': 34, 'torn': 34, 'like': 34, 'bulge': 34, 'sight': 34, 'associate': 34, 'personal': 34, 'lie': 34, 'wondering': 34, 'amazingly': 34, 'rust': 34, 'leaf': 34, 'tear': 34, 'hue': 34, 'nature': 34, 'ruined': 34, 'provide': 33, 'appeal': 33, 'contrasting': 33, 'pinned': 33, 'frayed': 33, 'printed': 33, 'finished': 33, 'boiled': 33, 'flutter': 33, 'appeared': 33, 'closely': 33, 'ridiculously': 33, 'pitch': 33, 'cap': 33, 'swallowed': 33, 'copper': 33, 'autumn': 33, 'stretching': 33, 'undergarment': 33, 'flowed': 33, 'mesh': 33, 'folded': 33, 'excess': 33, 'sucked': 33, 'reality': 33, 'goose': 32, 'remove': 32, 'forever': 32, 'broke': 32, 'annoying': 32, 'book': 32, 'reminded': 32, 'fear': 32, 'paying': 32, 'tough': 32, 'blanket': 32, 'minor': 32, 'puffed': 32, 'law': 32, 'hugging': 32, 'raise': 32, 'matron': 32, 'aesthetic': 32, 'shipped': 32, 'compare': 32, 'gape': 32, 'cleaning': 32, 'missed': 32, 'combined': 32, 'traditional': 32, 'bird': 32, 'strangely': 32, 'original': 32, 'mock': 32, 'total': 32, 'sheath': 32, 'major': 31, 'trace': 31, 'stuff': 31, 'hesitate': 31, 'opaque': 31, 'anticipated': 31, 'quick': 31, 'factor': 31, 'moving': 31, 'underwear': 31, 'saturated': 31, 'emphasized': 31, 'spare': 31, 'speaker': 31, 'hiding': 31, 'tassel': 31, 'cutlet': 31, 'reach': 31, 'setting': 31, 'strong': 31, 'gathering': 30, 'climate': 30, 'unbuttoned': 30, 'unexpected': 30, 'degree': 30, 'anna': 30, 'complimented': 30, 'decision': 30, 'horizontal': 30, 'knitted': 30, 'seamstress': 30, 'anymore': 30, 'depends': 30, 'appealing': 30, 'gather': 30, 'rate': 30, 'cut': 30, 'traveling': 30, 'draw': 30, 'easier': 29, 'world': 29, 'current': 29, 'fullness': 29, 'hitting': 29, 'worst': 29, 'obvious': 29, 'poly': 29, 'chiffon': 29, 'tightly': 29, 'marked': 29, 'shocked': 29, 'float': 29, 'wise': 29, 'creating': 29, 'silly': 29, 'bronze': 29, 'fill': 29, 'clot': 29, 'ample': 28, 'arrival': 28, 'highlight': 28, 'family': 28, 'church': 28, 'dragging': 28, 'uniqueness': 28, 'suspect': 28, 'raspberry': 28, 'shake': 28, 'dayti

## Saving required outputs
Save the requested information as per specification.
- vocab.txt

In [19]:
# Extract vocab
with open("vocabulary.txt", "w", encoding="utf-8") as f:
    for word, idx in vocab_dict.items():
        f.write(f"{word}:{idx}\n")

df.to_csv("processed.csv", index=False)

## Summary
Give a short summary and anything you would like to talk about the assessment task here.

## Couple of notes for all code blocks in this notebook
- please provide proper comment on your code
- Please re-start and run all cells to make sure codes are runable and include your output in the submission.   
<span style="color: red"> This markdown block can be removed once the task is completed. </span>